apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: md5-collator-2
  namespace: hashed-network
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - c2.md5.hashed.live
    - c2.md5.p2p.hashed.live
    secretName: md5-collator-2
  rules:
  - host: c2.md5.hashed.live
    http:
      paths:
      - pathType: Prefix
        path: /cp2p/
        backend:
          service:
            name: md5-collator-2
            port:
              number: 40333
      - pathType: Prefix
        path: /
        backend:
          service:
            name: md5-collator-2
            port:
              number: 9946
      - pathType: Prefix
        path: /rp2p/
        backend:
          service:
            name: md5-collator-2
            port:
              number: 30333
      - pathType: Prefix
        path: /rws/
        backend:
          service:
            name: md5-collator-2
            port:
              number: 9944
      - pathType: Prefix
        path: /rpc/
        backend:
          service:
            name: md5-collator-2
            port:
              number: 9933
  - host: c2.md5.p2p.hashed.network
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: md5-collator-2
            port:
              number: 40333
